### ISSUE TITLE
[request] Release built with GHC 7.10.3

### ISSUE THREAD

**Issue by fosskers** [rubik/stack-hpc-coveralls#11]
We're currently on `lts-5.x` for stack resolvers, which use ghc 7.10.3. Could you make a binary release built with 7.10.3?

Thank you kindly.

**Comment by rubik** [comment]
Sure. I've added it to the 0.0.3.0 release:
https://github.com/rubik/stack-hpc-coveralls/releases/tag/v0.0.3.0

**Comment by fosskers** [comment]
Thanks!
