### ISSUE TITLE
[request] Release built with GHC 8.0.1

### ISSUE THREAD

**Issue by fosskers** [rubik/stack-hpc-coveralls#15]
Same as last time :) Could you add a release binary built on GHC8? Please and thanks.

**Comment by rubik** [comment]
The latest Stack resolver is lts-6.3 and it still refers to GHC 7.10.3. How do you install the newer GHC with Stack?

**Comment by fosskers** [comment]
You'd have to use a nightly. LTS won't move to GHC8 until September, it's said.

**Comment by rubik** [comment]
Released v0.0.4.0 with the last changes.
https://github.com/rubik/stack-hpc-coveralls/releases/tag/v0.0.4.0

Please reopen if something does not work as expected, I'm not able to test it right now!

**Comment by fosskers** [comment]
Works!
