### ISSUE TITLE
Shc only supports stack 0.1.7

### ISSUE THREAD

**Issue by wayofthepie** [rubik/stack-hpc-coveralls#4]
I'm currently using stack 0.1.8.0, and running shc gives the following:

``` bash
Error: at least Stack 0.1.7 is required
```

Looks like the version check only supports stack 1.7.0: https://github.com/rubik/stack-hpc-coveralls/blob/master/src/SHC/Utils.hs#L57.

**Comment by rubik** [comment]
Argh, that was dumb on my part. Thanks for the PR.
