### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by rimmington** [rubik/stack-hpc-coveralls#7]
With stack 0.1.8.0 out, it'd be nice to have an official release with PR #6.

**Comment by rubik** [comment]
You're totally right! I pushed SHC 0.0.2.0 to Hackage and uploaded binaries here on Github.

**Comment by rimmington** [comment]
Alas, the 7.10.2 binary appears to actually be the 0.0.1.0 release. I haven't checked the 7.8.4 binary.

**Comment by rubik** [comment]
I'm sorry, that was a dumb error on my part. I uploaded the binaries again.
